version: '3'

services:
  database:
    container_name: hilde_db
    image: postgres:16
    environment:
      POSTGRES_DB: hilde
      POSTGRES_PASSWORD: hildepw
      POSTGRES_USER: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
